In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
p = pd.read_csv("MixedSet2.csv")

data = p

In [3]:
X =  data.iloc[:, :-1].values
print(X)
y = data.iloc[:, -1].values
print(y)


[[0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
['Lack of coolant'
 'The cooling system is clogged - it needs to be cleaned'
 'check the ventilation unit'
 'The alternator belt may be slipping or the

In [4]:
dimensionality_reduction = data.groupby(data['problem']).max()
print(dimensionality_reduction)


                                                    symptomA_Car exhaust smoke  \
problem                                                                          
A new head gasket may be needed                                              1   
Check for a vacuum leak or moisture in the dist...                           0   
Check if the air filter is clean. If so then ch...                           1   
Check the balance of the four wheels                                         0   
Lack of coolant                                                              0   
Matching problem between the brake pads and the...                           0   
The alternator belt may be slipping or the fan ...                           0   
The cooling system is clogged - it needs to be ...                           0   
The engine sensor may be damaged                                             1   
The engine sensor may be faulty                                              1   
This is a normal

In [5]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)
print(y)

[ 4  7 12  6  2  9  0 10 10  8  5  1  3  5 11  5]


In [6]:
model = tree.DecisionTreeClassifier()
model.fit(X,y)

DecisionTreeClassifier()

In [7]:
model


DecisionTreeClassifier()

In [8]:
cols     = data.columns
cols     = cols[:-1]

In [9]:
importances = model.feature_importances_
indices = np.argsort(importances)[::-1]
features = cols

In [10]:
from sklearn.tree import _tree

In [11]:
def execute_bot():

    print("Please reply with yes/Yes or no/No for the following symptoms") 
    def print_problem(node):
        #print(node)
        node = node[0]
        #print(len(node))
        val  = node.nonzero() 
        #print(val)
        problem = labelencoder.inverse_transform(val[0])
        return problem
    def tree_to_code(tree, feature_names):
        tree_ = tree.tree_
        #print(tree_)
        feature_name = [
            feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
            for i in tree_.feature
        ]
        symptoms_present = []
        def recurse(node, depth):
            indent = "  " * depth
            if tree_.feature[node] != _tree.TREE_UNDEFINED:
                name = feature_name[node]
                threshold = tree_.threshold[node]
                print(name + " ?")
                ans = input()
                ans = ans.lower()
                if ans == 'yes':
                    val = 1
                else:
                    val = 0
                if  val <= threshold:
                    recurse(tree_.children_left[node], depth + 1)
                else:
                    symptoms_present.append(name)
                    recurse(tree_.children_right[node], depth + 1)
            else:
                present_problem = print_problem(tree_.value[node])
                
                print('The Model Suggests:')
                print()
                print( "You may have: " +  present_problem )
                print()
                row = CarDiagnose[CarDiagnose['problem'] == present_problem[0]]
                print('Description: ', str(row['Description'].values))
                print()
                print('Inspection List: ', str(row['InspectionList'].values))
    
        recurse(0, 1)
    
    tree_to_code(model,cols)




In [17]:
""" D = pd.read_csv("CarDiagnose.csv") """
    
Isnpection_dataset = pd.read_csv("CarDiagnose.csv", names = ['Description','InspectionList'])

problem = dimensionality_reduction.index
problem = pd.DataFrame(problem)

CarDiagnose = pd.DataFrame()

CarDiagnose['Description'] = np.nan
CarDiagnose['InspectionList'] = np.nan

CarDiagnose['problem'] = np.nan
CarDiagnose['problem'] = problem['problem']


CarDiagnose['Description'] = Isnpection_dataset['Description']
CarDiagnose['InspectionList'] = Isnpection_dataset['InspectionList']


In [18]:
execute_bot()

Please reply with yes/Yes or no/No for the following symptoms
symptomA_The car shakes ?
symptomC_It only happens under heavy braking and there is no vibration from the front end ?
The Model Suggests:

['You may have: This is a normal situation. The anti lock system pulsates the brakes']

Description:  ['A serpentine belt is a rubber belt that is driven by pulleys connected to the engine, the belt then runs motors and pumps that are necessary to help keep your vehicle running. When your serpentine belt begins to make noise or is noticebly worn or damaged, its time to replace it. A bad serpentine belt can cause your vehicle to stall, steering to tighten up, and even overheat your vehicle.']

Inspection List:  ["1) Open the vehicles hood and locate the vehicles serpentine belt. 2) Inspect the ribs onthe serpentine belt.Check for cracks in the rubber, fraying, or chips to the belt. Look forsigns offluids that may have spilled on the belt. 3) Check the belt tension by pushing down in the mi

In [19]:
import pickle

filename = 'savedmodel.sav'
pickle.dump(model,open(filename,'wb'))

In [20]:
load_model = pickle.load(open(filename,'rb'))

In [21]:
""" load_model() """

TypeError: 'DecisionTreeClassifier' object is not callable